# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Butler < Formula
  desc "Multi-chain EVM wallet CLI tool for Chiliz Chain"
  homepage "https://github.com/GrapeInTheTree/go-ethereum-butler"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.6.0/butler_Darwin_x86_64.tar.gz"
      sha256 "1aa15635204509c4226bb46be84291a2d5602c0d7274c60278a4e5ddc032c060"

      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.6.0/butler_Darwin_arm64.tar.gz"
      sha256 "6bda4ebc2cbd98768543dd373c6c1ceb43db4fe4a18b883a9dd00256e76b1c1b"

      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.6.0/butler_Linux_x86_64.tar.gz"
      sha256 "9fa93a3d34eaf63724d2cf63609c6e59408a7b06da5069de0d61951138f9bfff"
      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.6.0/butler_Linux_arm64.tar.gz"
      sha256 "086955fe4115fe3e13bdff9de5d5dc8cbbd39a1f1ac2b37e96ff66dc77678a67"
      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  test do
    system "#{bin}/butler", "--help"
  end
end
