# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Butler < Formula
  desc "Multi-chain EVM wallet CLI tool for Chiliz Chain"
  homepage "https://github.com/GrapeInTheTree/go-ethereum-butler"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.2.0/butler_Darwin_x86_64.tar.gz"
      sha256 "3e2d774595dcb88c16fa8a2edc22a77ece6c36691baf0e2770d1a1570387dfb4"

      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.2.0/butler_Darwin_arm64.tar.gz"
      sha256 "82f5ba04c9942266225a4f3ec48971f3ea6aa83af4b665bce36475806183f362"

      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.2.0/butler_Linux_x86_64.tar.gz"
      sha256 "ef68dd5b38c1762babeea5f04fd56334667fa686f267c999604a7ffe0a038245"
      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.2.0/butler_Linux_arm64.tar.gz"
      sha256 "638c7195727063baef963029fd1e9e498b711531996a39476063fbee2c476341"
      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  test do
    system "#{bin}/butler", "--help"
  end
end
