# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Butler < Formula
  desc "Multi-chain EVM wallet CLI tool for Chiliz Chain"
  homepage "https://github.com/GrapeInTheTree/go-ethereum-butler"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.7.0/butler_Darwin_x86_64.tar.gz"
      sha256 "eaebf66f33192fdfa908a3c9cc18ddb8ce2a8abafaf05e1d698d945cb836f64e"

      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.7.0/butler_Darwin_arm64.tar.gz"
      sha256 "f0d964bf593704a1ea55a6c4752dcae1b04cae85b5b7f60b3236727e9427f862"

      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.7.0/butler_Linux_x86_64.tar.gz"
      sha256 "8c0b69a9b4f8e20317d473a52977b5e97b64e5e77944c2e254a161e55142fa5a"
      define_method(:install) do
        bin.install "butler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/go-ethereum-butler/releases/download/v0.7.0/butler_Linux_arm64.tar.gz"
      sha256 "304bc07533a3e5c08bcecbbc3aae2d74d5f05722b1f8ddbc732dba36ddba7dc7"
      define_method(:install) do
        bin.install "butler"
      end
    end
  end

  test do
    system "#{bin}/butler", "--help"
  end
end
