# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiliz < Formula
  desc "The CLI for Chiliz Chain — validators, staking, tokens, contracts"
  homepage "https://github.com/GrapeInTheTree/chiliz-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrapeInTheTree/chiliz-cli/releases/download/v1.0.0/chiliz_Darwin_x86_64.tar.gz"
      sha256 "c5cc79762bc855ec7b41f9897cc2bd7539f8e5ed5b6dbc9961f1488d92552306"

      define_method(:install) do
        bin.install "chiliz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GrapeInTheTree/chiliz-cli/releases/download/v1.0.0/chiliz_Darwin_arm64.tar.gz"
      sha256 "b17df55caa50807cd3a04b3807aeb0db3e14f91b68f3c483d10b20285404351e"

      define_method(:install) do
        bin.install "chiliz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/chiliz-cli/releases/download/v1.0.0/chiliz_Linux_x86_64.tar.gz"
      sha256 "db20c4c14bfcbf9dfbe5f0781b815292dcbd58ff3c992ae71909b6b153236649"
      define_method(:install) do
        bin.install "chiliz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrapeInTheTree/chiliz-cli/releases/download/v1.0.0/chiliz_Linux_arm64.tar.gz"
      sha256 "b7769318b5afdc99fe88861fdcea6432beff1afa3a9750d2b50b86eefeefeaec"
      define_method(:install) do
        bin.install "chiliz"
      end
    end
  end

  test do
    system "#{bin}/chiliz", "--help"
  end
end
